### ISSUE TITLE
Simplified Metadata Schema for v1.0

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#393]
See https://github.com/geoblacklight/geoblacklight-schema for current schema. See #423 for v2.0 changes.

Tasks:
- [x] Update documentation for GeoBlacklight-Schema -- https://github.com/geoblacklight/geoblacklight-schema/pull/89

Deprecate:
- [x] Deprecate `uuid` -- see https://github.com/geoblacklight/geoblacklight-schema/issues/53
- [x] Deprecate `dc_relation_sm` (keep `dct_isPartOf_sm ` which is currently being used for collections) -- see https://github.com/geoblacklight/geoblacklight-schema/issues/85
- [x] Deprecate `solr_year_i` (only used by the Blacklight range plugin, not core GeoBlacklight, and generally you want a multi-valued field here) -- see https://github.com/geoblacklight/geoblacklight-schema/issues/90
- [x] Deprecate `georss_box_s`, `georss_point_s` and `georss_polygon_s` (all unused)

Adding:
- [x] Add `dc_source_sm` for derived layers -- see #412 and https://github.com/geoblacklight/geoblacklight-schema/issues/83
- [x] Add `geoblacklight_version ` for schema version of record

**Comment by mejackreed** [comment]
Maybe now `*_srpt` ?

**Comment by mejackreed** [comment]
Also make sure to loop in #412 and https://github.com/geoblacklight/geoblacklight-schema/issues/83

**Comment by drh-stanford** [comment]
possibly drop `dc_relation_sm` and keep `dct_isPartOf_sm`

**Comment by drh-stanford** [comment]
For changing/relocating, we can 
* [ ] submit PR to OpenGeoMetadata
* [ ] change GeoCombine
* [ ] add directions in GeoBlacklight upgrade guide
  * [ ] each institution would implement

**Comment by andrewbattista** [comment]
This looks good! I think I was talking with @sgbalogh yesterday about some of the implications of this

**Comment by drh-stanford** [comment]
To deprecate `uuid` and `dc_identifier_s` in favor of `layer_slug_s` we need to update the Solr `schema.xml` here:

https://github.com/geoblacklight/geoblacklight/blob/master/schema/solr/conf/schema.xml#L3

and switch `uuid` from required = `true` to `false`

**Comment by drh-stanford** [comment]
I added some documentation for the `solr_year_i` field deprecation -- but left the fields in the fixture data. thoughts on what to do with `solr_year_i` for v1.0?

**Comment by mejackreed** [comment]
Is adding `dc_source_sm` something we want to commit to for 1.0? Or can we wait until 1.1?

**Comment by mejackreed** [comment]
Also is `georss_box` something we could also drop here?

**Comment by eliotjordan** [comment]
I don't think we need `georss_box`.

**Comment by drh-stanford** [comment]
`georss_box_s` is the bounding box in the standardized GeoRSS format, and `solr_geom` is the bounding box in the Solr format which is derived from `georss_box_s`. Perhaps now that we're encouraging the `ENVELOPE` syntax there isn't as much confusion as there used to be about the structure of the bounding box. All of our fixtures use the `ENVELOPE` syntax, for example.  Not sure about OpenGeoMetadata contributions though.

`dc_source_sm` is only a documentation change. The core code doesn't use it.

**Comment by drh-stanford** [comment]
the outstanding issues here are with the fields `solr_year_i` and `georss_box_s`

**Comment by mejackreed** [comment]
Hm. Yeah I guess the question here is. Should we have the field that is used only to derive another field from?

This kind of starts to go to the question about having Solr handling some of it. I think what we are thinking about is a custom Data Import Handler? https://wiki.apache.org/solr/DIHCustomTransformer

**Comment by andrewbattista** [comment]
In cases like what you are describing, Jack, is there any benefit at all for redundancy (in terms of how the technology functions)? I think this is the question has has been lurking over several elements of the initial iteration of the schema

**Comment by mejackreed** [comment]
No one that we can tell is using these redundant elements (`georss_*`). The technology doesn't use it currently. It provides potentially for something later on, but @drh-stanford and I were just discussing we probably don't need it.

**Comment by drh-stanford** [comment]
Yeah!
