### ISSUE TITLE
Metadata changes for v3.0

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight#423]
See #393.

This issue spans multiple projects and is meant to coordinate making schema changes in various codebases/institutions.

Renaming:
- [x] Rename `layer_slug_s` into `id` -- see https://github.com/geoblacklight/geoblacklight-schema/issues/53
- [x] Change `dc_language_s` to `dc_language_sm` -- see https://github.com/geoblacklight/geoblacklight-schema/issues/67
- [ ] Rename `solr_geom` to `solr_srpt` (to tie to Solr [schema datatype](https://cwiki.apache.org/confluence/display/solr/Spatial+Search#SpatialSearch-SpatialRecursivePrefixTreeFieldType%28abbreviatedasRPT%29))

Relocating:
- [ ] Move `layer_id_s` into `dct_references_s` as `http://www.opengis.net/def/serviceType/ogc/wfs#layer_id` -- see https://github.com/geoblacklight/geoblacklight-schema/issues/77

For changing/relocating, we can 
- [ ] submit PR to OpenGeoMetadata
- [ ] change GeoCombine
- [ ] add directions in GeoBlacklight upgrade guide
  - [ ] each institution would implement

**Comment by kgjenkins** [comment]
We should consider these for the next version of the GBL schema, or else close this issue.

**Comment by karenmajewicz** [comment]
I don't think I have ever even looked at this issue! I think we should review at it while we analyze the schema, as there are some relevant ideas here.

**Comment by karenmajewicz** [comment]
We have addressed several items in this issue. Closing for now as the remaining items are no longer relevant.
